### PR TITLE
Install apsw as a package to get .pyi install right

### LINKED ISSUE #327: Stub .pyi file invalid location
The .pyi stub file is installed to an invalid location: to the system prefix catalog (e.g. "/usr") instead of "python sitearch".
```
error: Installed (but unpackaged) file(s) found:
   /usr/apsw.pyi
```
As a workaround, the file can be moved to the proper location by hands — but better to fix this behavior.

It looks like maintainers are trying to follow https://peps.python.org/pep-0484 rather than the later https://peps.python.org/pep-0561/. However, the way they are installing the stub file with data_files in setup.py is resulting in it getting dumped in %_prefix.

### PR DESCRIPTION
**Pull request by mgorny**
Install apsw as a package, with the C extension becoming apsw.\_\_init__,
and install the .pyi file inside it.  This is probably the least hacky
way to fix .pyi install path while preserving maximum compatibility.

Fixes #327

### CODE REVIEW

**Comment by rogerbinns** [comment]
Thanks for doing this.  Looks like I can also add PEP 561 magic filename.  I'm currently working on getting apsw into pypi and then will move onto this.

**Comment by rogerbinns** [comment]
Your solution is ingenious and works well, except on Windows which gets the wrong idea of the entrypoint.  Working on fixing that.

**Comment by rogerbinns** [comment]
The approach is now in 3.38.5-r1 and works perfectly.  Thank you.

**Comment by mgorny** [comment]
Yeah, I can confirm that the release installs fine! Thank you!

**Pull request closed without merging**
