### PR TITLE
README.rst: Add PyPI badge

### PR DESCRIPTION
**Pull request by msabramo**
Preview at https://github.com/msabramo/apsw/blob/patch-1/README.rst

### CODE REVIEW

**Comment by rogerbinns** [comment]
APSW is not on pypi as the docs state including why http://rogerbinns.github.io/apsw/download.html#easy-install-pip-pypi

Someone else has put on something with the same name which won't build for most people, is outdated, and no verification it is even the right code.  Consequently not merging this.

**Comment by msabramo** [comment]
Ah sorry for that. It confused me because I didn't see that note in the docs and the PyPI entry had your name and git repo (although looking at it now I see the package index owner is rstuart which I hadn't noticed before). 

This is interesting because I am a maintainer of pymssql and I have struggled with the same issue because I wanted to offer an option to bundle our dependency, FreeTDS. 

So I may borrow from your approach and I might try to come up with something that works better with pip, as I've contributed on occasion to pip. 

One thing that works that pymssql does a bit of is to use environment variables. Those can be specified on the command line and they propagate through to setup.py. 

I'll let you know if I come up with something better.

**Comment by msabramo** [comment]
I imagine that you tried `pip --install-option` (See https://pip.pypa.io/en/latest/reference/pip_install.html#options) and it didn't work for your case? Maybe because it can pass options but not arguments/commands like "fetch"?

**Comment by rogerbinns** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 01/28/2015 07:13 PM, Marc Abramowitz wrote:
> Ah sorry for that. It confused me because I didn't see that note in
> the docs and the PyPI entry had your name and git repo (although
> looking at it now I see the package index owner is rstuart which I
> hadn't noticed before).

I did contact rstuart before and he did have text in the page saying
it was unofficial and also fixed the code he put there which wasn't a
release just a random zip of master.  There have been 5 releases since
he did that and I pointed out the other day that the page also needs
to say it is way out of date.  So instead he removed all the other
text and now implies that it is official and up to date, unless the
page is examined very carefully.

> So I may borrow from your approach and I might try to come up with 
> something that works better with pip, as I've contributed on
> occasion to pip.

pip really sucks for customisation.  I'm increasingly tempted to make
something I upload to pypi that is just hard coded to always do a
certain set of things.  Tough luck to anyone who wanted it different.

> One thing that works that pymssql does a bit of is to use
> environment variables. Those can be specified on the command line
> and they propagate through to setup.py.

I also need setup.py subcommands run too (eg fetch).  If I could
include something in the zip for pip to look at then all would be
well.  This is what is best run:

  python setup.py fetch --all --version=3.8.8.1 build
- --enable-all-extensions install test

Roger
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlTJp10ACgkQmOOfHg372QQO6wCfVqOFxJQQa8dfUhkCN1YDD6q7
uOkAn2esfDG7G54XX+N2SuWlua89Jx2w
=mUaG
-----END PGP SIGNATURE-----

**Comment by rogerbinns** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 01/28/2015 07:19 PM, Marc Abramowitz wrote:
> I imagine that you tried |pip --install-option| (See 
> https://pip.pypa.io/en/latest/reference/pip_install.html#options)
> and it didn't work for your case? Maybe because it can pass options
> but not arguments/commands like "fetch"?

install is the one subcommand that doesn't need options in my case.
It is fetch and build that need them.

Roger

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iEYEARECAAYFAlTJp6kACgkQmOOfHg372QSeRQCgwaPqMGrIXfdKJbcsmkhda16g
LXkAoM5922nbyvaDYgwey6UswQnyd6kN
=5ihS
-----END PGP SIGNATURE-----

**Pull request closed without merging**
